name: Build
on:
    workflow_dispatch:
        inputs:
            publish:
                description: Publish to CurseForge and Modrinth
                required: true
                default: "false"
    pull_request:
    push:

jobs:
  build:
    strategy:
      matrix:
        java: [17]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      CURSEFORGE_TOKEN: ${{secrets.CURSEFORGE_TOKEN}}
      MODRINTH_TOKEN: ${{secrets.MODRINTH_TOKEN}}
    steps:
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build -PuseThirdPartyMods=false
      - name: Extract current branch name
        shell: bash
        # bash pattern expansion to grab branch name without slashes
        run: ref="${GITHUB_REF#refs/heads/}" && echo "::set-output name=branch::${ref////-}"
        id: ref
      - name: Capture Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FrozenLib-Artifacts-${{ steps.ref.outputs.branch }}
          path: build/libs/
      - name: Publish to CurseForge and Modrinth
        if: ${{github.events.input.publish}}
        run: ./gradlew publishMod
